KlassiDBtarpe23/Models/ErrorViewModel.cs
namespace KlassiDBtarpe23.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

KlassiDBtarpe23/Controllers/ClassController.cs
using KlassiDBtarpe23.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KlassiDBtarpe23.Controllers
{
    public class ClassController : Controller
    {
        private readonly KlassiDBtarpe23DbContext _context;

        public ClassController(KlassiDBtarpe23DbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var KlassiDBtarpe23DbContext = _context.Class;
            return View(await KlassiDBtarpe23DbContext.ToListAsync());
        }
    }
}

KlassiDBtarpe23/Controllers/CouponController.cs
using KlassiDBtarpe23.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KlassiDBtarpe23.Controllers
{
    public class CouponController : Controller
    {
        private readonly KlassiDBtarpe23DbContext _context;

        public CouponController(KlassiDBtarpe23DbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var KlassiDBtarpe23DbContext = _context.Coupon;
            return View(await KlassiDBtarpe23DbContext.ToListAsync());
        }
    }
}

KlassiDBtarpe23/Controllers/HomeController.cs
using KlassiDBtarpe23.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace KlassiDBtarpe23.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

KlassiDBtarpe23/Controllers/InstructorController.cs
using KlassiDBtarpe23.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KlassiDBtarpe23.Controllers
{
    public class InstructorController : Controller
    {
        private readonly KlassiDBtarpe23DbContext _context;

        public InstructorController(KlassiDBtarpe23DbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var KlassiDBtarpe23DbContext = _context.Instructor;
            return View(await KlassiDBtarpe23DbContext.ToListAsync());
        }
    }
}

KlassiDBtarpe23/Controllers/StudentController.cs
using KlassiDBtarpe23.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace KlassiDBtarpe23.Controllers
{
    public class StudentController : Controller
    {
        private readonly KlassiDBtarpe23DbContext _context;

        public StudentController(KlassiDBtarpe23DbContext context)
        {
            _context = context;
        }
        public async Task<IActionResult> Index()
        {
            var KlassiDBtarpe23DbContext = _context.Student;
            return View(await KlassiDBtarpe23DbContext.ToListAsync());
        }
    }
}

KlassiDBtarpe23/Views/Class/Index.cshtml
@model IEnumerable<KlassiDBtarpe23.Core.Domain.Class>
@{
    ViewData["Title"] = "Klassid";
}

<h2>Klassid</h2>

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.ClassID)</th>
            <th>@Html.DisplayNameFor(model => model.ClassName)</th>                    
        </tr>
    </thead>
    <tbody>
        @foreach (var Class in Model)
        {

            <tr>
                <td>@Html.DisplayFor(modelItem => Class.ClassID)</td>
                <td>@Html.DisplayFor(modelItem => Class.ClassName)</td>             
            </tr>
        }     
    </tbody>
</table>

KlassiDBtarpe23/Views/Coupon/Index.cshtml
@model IEnumerable<KlassiDBtarpe23.Core.Domain.Coupon>
@{
    ViewData["Title"] = "Kupongid";
}

<h2>Kupongid</h2>

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.CouponID)</th>
            <th>@Html.DisplayNameFor(model => model.StudentName)</th>
            <th>@Html.DisplayNameFor(model => model.Date)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var coupon in Model)
        {

            <tr>
                <td>@Html.DisplayFor(modelItem => coupon.CouponID)</td>
                <td>@Html.DisplayFor(modelItem => coupon.StudentName)</td>
                <td>@Html.DisplayFor(modelItem => coupon.Date)</td>
            </tr>
        }
    </tbody>
</table>

KlassiDBtarpe23/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

KlassiDBtarpe23/Views/Instructor/Index.cshtml
@model IEnumerable<KlassiDBtarpe23.Core.Domain.Instructor>
@{
    ViewData["Title"] = "KlassiJuhatajad";
}

<h2>KlassiJuhatajad</h2>

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.InstructorID)</th>
            <th>@Html.DisplayNameFor(model => model.InstructorName)</th>
            <th>@Html.DisplayNameFor(model => model.ClassAssignments)</th>
            <th>@Html.DisplayNameFor(model => model.ClassName)</th>
            <th>@Html.DisplayNameFor(model => model.Gender)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var instructor in Model)
        {

            <tr>
                <td>@Html.DisplayFor(modelItem => instructor.InstructorID)</td>
                <td>@Html.DisplayFor(modelItem => instructor.InstructorName)</td>
                <td>@Html.DisplayFor(modelItem => instructor.ClassAssignments)</td>
                <td>@Html.DisplayFor(modelItem => instructor.ClassName)</td>
                <td>@Html.DisplayFor(modelItem => instructor.Gender)</td>
            </tr>
        }
    </tbody>
</table>

KlassiDBtarpe23/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KlassiDBtarpe23</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/KlassiDBtarpe23.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KlassiDBtarpe23</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Class" asp-action="Index">Klassid</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Õpilased</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Instructor" asp-action="Index">Klassijuhatajad</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Coupon" asp-action="Index">Söögikupongid</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - KlassiDBtarpe23 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

KlassiDBtarpe23/Views/Student/Index.cshtml
@model IEnumerable<KlassiDBtarpe23.Core.Domain.Student>
@{
    ViewData["Title"] = "Õpilased";
}

<h2>Õpilased</h2>

<table class="table">
    <thead>
        <tr>
            <th>@Html.DisplayNameFor(model => model.StudentID)</th>
            <th>@Html.DisplayNameFor(model => model.StudentName)</th>
            <th>@Html.DisplayNameFor(model => model.ClassName)</th>         
            <th>@Html.DisplayNameFor(model => model.Age)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var student in Model)
        {

            <tr>
                <td>@Html.DisplayFor(modelItem => student.StudentID)</td>
                <td>@Html.DisplayFor(modelItem => student.StudentName)</td>
                <td>@Html.DisplayFor(modelItem => student.ClassName)</td>
                <td>@Html.DisplayFor(modelItem => student.Age)</td>
            </tr>
        }
    </tbody>
</table>